pipeline {

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        disableConcurrentBuilds()
    }

agent {
        node {
            label 'docker-slave-macos-maven-java'
        }
    }

    stages {

        stage('Build & TEST') {
            steps {
                    sh 'mvn clean install'
		            sh 'mvn exec:java'
            }
        }
    }
}
